export const projectsData = [
  {
    id: "1",
    name: "C-11J",
    period: "2016/03",
    category: "ロケット",
    thumbnail: "/11.jpg",
    altitude: "1130m",
    length: "1077mm",
    weight: "2.05kg",
    caption: "機体を超軽量化しJ型エンジンを用いた高高度化を目指した。団体初の高度1 km越えを達成した。",
    captionEn: "Aimed for high altitude using a J-type engine with an ultra-lightweight airframe. Achieved the organization's first altitude exceeding 1 km.",
    periodEn: "2016/03"
  },
  {
    id: "2",
    name: "C-29J",
    period: "2017/11",
    category: "ロケット",
    thumbnail: "/29.jpg",
    altitude: "750m（参考値）",
    length: "1560mm",
    weight: "3.737kg",
    caption: "機体に載せた缶サットを上空で放出し、缶サットに搭載された風船を用いた減速落下を目指した。",
    captionEn: "Released a CanSat from the rocket in mid-air, aiming for a decelerated descent using a balloon mounted on the CanSat.",
    periodEn: "2017/11"
  },
  {
    id: "3",
    name: "C-31J",
    period: "2017/11",
    category: "ロケット",
    thumbnail: "/31.jpg",
    altitude: "700m",
    length: "1735mm",
    weight: "3.365kg",
    caption: "2017年度新入生機体。2段式ロケットに必要な要素技術（分離部の構造，上空でのモデルロケットエンジンの点火）の検証のための機構を搭載した。検証機体",
    captionEn: "2017 Freshman Project. Equipped with mechanisms to verify elemental technologies required for a two-stage rocket (separation structure, mid-air ignition of model rocket engine). Verification model.",
    periodEn: "2017/11"
  },
  {
    id: "4",
    name: "J-i",
    period: "2018/03",
    category: "エンジン",
    thumbnail: "/j-i.jpg",
    thrust: "-------",
    burnCount: "------",
    caption: "CREATEが制作した初めての自作エンジン。酸化剤のリークにより燃焼には至らなかったものの、これにより得られた知見は以後の自作エンジン設計・製作に大きく生かされた。",
    captionEn: "CREATE's first custom-made engine. Although it did not reach combustion due to an oxidizer leak, the knowledge gained was greatly utilized in subsequent custom engine design and production.",
    periodEn: "2018/03"
  },
  {
    id: "5",
    name: "C-37K",
    period: "2018/08",
    category: "ロケット",
    thumbnail: "/37.jpg",
    altitude: "",
    length: "1463mm",
    weight: "3.69kg",
    caption: "海打ちのための水密機構と電装への衝撃を緩和する機構を導入した。また機体側部にカメラを搭載し動画撮影を試みた。",
    captionEn: "Introduced a watertight mechanism for sea launch and a mechanism to mitigate shock to avionics. Also attempted video recording with a camera mounted on the side of the airframe.",
    periodEn: "2018/08"
  },
  {
    id: "6",
    name: "C-41J",
    period: "2018/11",
    category: "ロケット",
    thumbnail: "/41.jpg",
    altitude: "511m",
    length: "1520.5mm",
    weight: "3.775kg",
    caption: "2018年度新入生機体。機体に缶サットを搭載し、上空で放出。缶サットに搭載された煙玉に点火し，空中に煙で落下の軌跡を描くことを目指した。",
    captionEn: "2018 Freshman Project. Carried a CanSat and released it in mid-air. Aimed to ignite a smoke ball on the CanSat to trace the fall trajectory with smoke.",
    periodEn: "2018/11"
  },
  {
    id: "7",
    name: "J-2i",
    period: "2019/07/14",
    category: "エンジン",
    thumbnail: "/j-2i.jpg",
    thrust: "120N",
    burnCount: "2回",
    caption: "CREATEが制作した自作エンジンのエンジニアリングモデル。J-2iはCREATE史上初めて燃焼に成功した自作エンジンである。",
    captionEn: "Engineering model of CREATE's custom engine. J-2i is the first custom engine in CREATE's history to successfully combust.",
    periodEn: "2019/07/14"
  },
  {
    id: "8",
    name: "C-43J(COSMOS)",
    period: "2019/11",
    category: "ロケット",
    thumbnail: "/43.jpg",
    altitude: "155m",
    length: "2010mm",
    weight: "8.243kg",
    caption: "団体初の2段式ロケット。姿勢不安定のため2段目の点火には至らなかった一方、機体と高速ロギングされたデータの回収には成功した。",
    captionEn: "The organization's first two-stage rocket. While the second stage did not ignite due to attitude instability, the airframe and high-speed logged data were successfully recovered.",
    periodEn: "2019/11"
  },
  {
    id: "9",
    name: "C-47J",
    period: "2019/12",
    category: "ロケット",
    thumbnail: "/47.jpg",
    altitude: "434.5m（参考値）",
    length: "1606mm",
    weight: "5.716kg",
    caption: "2019年度新入生機体。着地衝撃の緩和と落下分散の縮小を目指しエアバッグ機構を搭載した。",
    captionEn: "2019 Freshman Project. Equipped with an airbag mechanism to mitigate landing shock and reduce landing dispersion.",
    periodEn: "2019/12"
  },
  {
    id: "10",
    name: "J-3i(ΕΛΠΙΣ)",
    period: "2020/02/29",
    category: "エンジン",
    thumbnail: "/j-3i.jpg",
    thrust: "300N",
    burnCount: "3回",
    caption: "CREATE初の自作エンジンのフライトモデル。J-3iは2021年11月にC-53J+3iに搭載されて無事打ち上がった。",
    captionEn: "Flight model of CREATE's first custom engine. J-3i was successfully launched aboard C-53J+3i in November 2021.",
    periodEn: "2020/02/29"
  },
  {
    id: "11",
    name: "C-53J+J-3i(COMPASS)",
    period: "2021/11/07",
    category: "ロケット",
    thumbnail: "/53.jpg",
    altitude: "112.6m",
    length: "1694.5mm",
    weight: "8.706kg",
    caption: "団体初の自作エンジンJ-3i及び2軸カメラジンバル搭載機。機体と電装データの回収に成功した。",
    captionEn: "First rocket equipped with custom engine J-3i and a 2-axis camera gimbal. Successfully recovered the airframe and avionics data.",
    periodEn: "2021/11/07"
  },
  {
    id: "12",
    name: "C-59J(Iris)",
    period: "2022/11/13",
    category: "ロケット",
    thumbnail: "/59.jpg",
    altitude: "353.1m",
    length: "1541mm",
    weight: "5.944kg",
    caption: "団体初の動翼を用いたロール制御を行った。回収した電装データと機体搭載カメラによりロール制御の成功を確認した。",
    captionEn: "Performed roll control using active fins for the first time. Confirmed success via recovered data and onboard camera footage.",
    periodEn: "2022/11/13"
  },
  {
    id: "13",
    name: "C-61J(UNICORN)",
    period: "2022/11/12",
    category: "ロケット",
    thumbnail: "/61.jpg",
    altitude: "383.4m",
    length: "1462mm",
    weight: "5.652kg",
    caption: "2021年度新入生機体。無線通信によって情報をリアルタイム表示することと、飛び出したカメラによる撮影に挑戦し、飛び出したカメラによる撮影に成功した。",
    captionEn: "2021 Freshman Project. Attempted real-time data display via wireless communication and filming with an ejected camera. Successfully filmed with the ejected camera.",
    periodEn: "2022/11/12"
  },
  {
    id: "14",
    name: "C-67J(海月)",
    period: "打上を断念",
    category: "ロケット",
    thumbnail: "/67.jpg",
    altitude: "748.0m (シミュ値)",
    length: "1630mm",
    weight: "4.096kg",
    caption: "2022年度新入生機体。パラシュートの開傘衝撃を和らげるためのリーフィング機構と、機体の軽量化に挑戦する。",
    captionEn: "2022 Freshman Project. Challenged reefing mechanism to mitigate parachute opening shock and airframe weight reduction.",
    periodEn: "Launch Aborted"
  },
  {
    id: "15",
    name: "C-71J(NOVA)",
    period: "2023/11/25",
    category: "ロケット",
    thumbnail: "/71.jpg",
    altitude: "150.4m",
    length: "1900mm",
    weight: "7.737kg",
    caption: "団体初のバルブシステムと縦型開放機構、外部給電を採用した機体。回収した統合基板のデータから推力が誤差範囲内に収まったことを確認した。",
    captionEn: "First rocket to adopt a valve system, vertical release mechanism, and external power supply. Confirmed thrust was within error margin from recovered data.",
    periodEn: "2023/11/25"
  },
  {
    id: "16",
    name: "C-73J(DaC)",
    period: "2025/03/18",
    category: "ロケット",
    thumbnail: "/73.jpg",
    altitude: "1156m (シミュ値)",
    length: "1833mm",
    weight: "6.015kg",
    caption: "リアルタイム映像伝送とジンバル制御に挑戦した機体。また、団体内初の自作タンクを搭載しての打上げに成功した。",
    captionEn: "Challenged real-time video transmission and gimbal control. Also successfully launched with the organization's first custom-made tank.",
    periodEn: "2025/03/18"
  },
  {
    id: "17",
    name: "C-79J(雪風)",
    period: "2024/03/28",
    category: "ロケット",
    thumbnail: "/79.jpg",
    altitude: "不明",
    length: "1704mm",
    weight: "6.100kg",
    caption: "2023年度新入生機体。C-41J以来となる空中でのCanSat放出を行った。機体捜索補助用の煙玉発煙とCanSatによる中継通信をミッションとしたが、いずれも達成しなかった。",
    captionEn: "2023 Freshman Project. Released a CanSat in mid-air for the first time since C-41J. Missions were smoke emission for search aid and relay communication by CanSat, but neither was achieved.",
    periodEn: "2024/03/28"
  },
  {
    id: "18",
    name: "LM-5i",
    period: "2025/01",
    category: "エンジン",
    thumbnail: "/IMG_9048.jpg",
    thrust: "-- N",
    burnCount: "--",
    caption: "---",
    captionEn: "---",
    periodEn: "2025/01"
  },
  {
    id: "19",
    name: "C-83LM(キーちゃん)",
    period: "2025/08",
    category: "ロケット",
    thumbnail: "/83.jpg",
    altitude: "N/A",
    length: "2252mm",
    weight: "17.105kg",
    caption: "機体高高度化に向けて開発した機体。「バルブシステム×自作エンジンの開発」「縦型開放機構×リーフィング機構の開発」に挑戦した。飛翔中のエンジントラブルにより、推力を失い海に落下したため、フルサクセスの達成はならなかった。機構および自作エンジンの地上試験には成功した。",
    captionEn: "Developed a body for high altitude. Challenged the development of 'valve system x custom engine' and 'vertical opening mechanism x lifting mechanism'. Failed to achieve full success due to engine failure during flight. Successfully tested mechanisms and custom engines on the ground.",
    periodEn: "2025/08"
  },
  {
    id: "20",
    name: "C-89J(白)",
    period: "打ち上げ断念",
    category: "ロケット",
    thumbnail: "/89.jpg",
    altitude: "313m (シミュ値)",
    length: "1698mm",
    weight: "6.652kg",
    caption: "2024年度新入生機体。二段階構造フィンとピトー管に挑戦した機体。プレ現地審査におち、東京で作り直したものを改めて現地に持って行ったが、強風のため打ち上げを断念した。",
    captionEn: "2024 Freshman Project. Challenged two-stage fins and pitot tube. Failed pre-site inspection, rebuilt in Tokyo, but launch was aborted due to strong winds at the site.",
    periodEn: "Launch Aborted"
  },
  {
    id: "21",
    name: "C-04R",
    period: "2025/08",
    category: "CanSat",
    thumbnail: "/c-04R.jpg",
    altitude: "N/A",
    length: "N/A",
    weight: "N/A",
    caption: "CREATE初のランバック機体。自律走行によりゴールへの到達を目指した。",
    captionEn: "CREATE's first runback rover. Aimed to reach the goal via autonomous driving.",
    periodEn: "2025/08"
  },
]
